/**
 * IMAGE OBJECT
 *
 * This is the Image for MongoDB in mongoose.Schema
 * Note : _id is generated by MongoDB and is the same _id
 */
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

// set up a mongoose model and pass it using module.exports
module.exports = mongoose.model('Image', new Schema({
    data: Buffer,
    contentType: String
}));